### ISSUE TITLE
Import Errors in scripts/multi_head_nn.py and scripts/multi_obj_nn.py

### ISSUE THREAD

**Issue by yassineCh** [lamda-bbo/offline-moo#3]
The scripts `scripts/multi_head_nn.py` and `scripts/multi_obj_nn.py` are importing `mo_solver` from the `algorithm` folder. I had to change it to import from `off_moo_baselines` to run the scripts. 
Additionally, the hv function is missing the task_name argument:

hv_value = hv(nadir_point, res_y)
TypeError: hv() missing 1 required positional argument: 'task_name'

Please update the import paths or clarify the correct structure.

Thank you for your support.

**Comment by trxcc** [comment]
Hi @yassineCh 

Thanks for your issue!

After checking our source code, I found some bugs in ``scripts/multi_head_nn.py`` and ``scripts/multi_head_nn.py``, which may have been caused by errors during our maintenance of the newer version of the code (under the ``off_moo_baselines`` directory). The bugs have now been fixed.

If you have any questions, feel free to contact us.

**Comment by yassineCh** [comment]
Thank you for the quick fix. You still need to update `scripts/multi_obj_nn.py` and `scripts/run_mobo_once.py` to add task_name when calling `hv()`.

**Comment by trxcc** [comment]
Thank you for your suggestion. We have updated ``scripts/multi_obj_nn.py`` and ``script/run_mobo_once.py``.
